version: '3'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=email@yourdomain.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    image: nginx:alpine
    container_name: example-webapp
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=app1.yourdomain.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=app1.yourdomain.com
      - LETSENCRYPT_EMAIL=email@yourdomain.com
    restart: always

  whoami:
    image: jwilder/whoami
    container_name: whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=app3.yourdomain.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=app3.yourdomain.com
      - LETSENCRYPT_EMAIL=email@yourdomain.com
    restart: always

  app:
    build: app
    container_name: app
    depends_on:
      - redis
    expose:
      - "5000"
    volumes:
      - ./app:/code
    environment:
      - FLASK_ENV=development
      - VIRTUAL_HOST=app2.yourdomain.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=app2.yourdomain.com
      - LETSENCRYPT_EMAIL=email@yourdomain.com
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  default:
    name: nginx-proxy
    external: true
